apiVersion: v2
name: nextcloud
description: A Helm chart for Nextcloud homelab deployment
type: application
version: 0.1.0
appVersion: "28"
keywords:
  - nextcloud
  - file-sharing
  - cloud-storage
home: https://nextcloud.com/
sources:
  - https://github.com/nextcloud/nextcloud
maintainers:
  - name: homelab
    email: admin@homelab.local
dependencies:
  - name: mysql
    version: "9.12.5"
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled