{{- if .Values.externalSecrets.enabled }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nextcloud.fullname" . }}-admin
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "nextcloud.fullname" . }}-admin
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: nextcloud-admin
      property: username
  - secretKey: password
    remoteRef:
      key: nextcloud-admin
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nextcloud.fullname" . }}-db-password
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "nextcloud.fullname" . }}-db-password
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: nextcloud-db-password
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nextcloud.fullname" . }}-mysql-root
  labels:
    {{- include "nextcloud.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore }}
    kind: SecretStore
  target:
    name: {{ include "nextcloud.fullname" . }}-mysql-root
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: mysql-root-password
      property: password
{{- end }}